apis:
  service.controller.hue:
    name: Hue Controller
    prefix: service.controller.hue
    upstream_url: http://service.controller.hue
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.controller.infrared:
    name: Infrared Controller
    prefix: service.controller.infrared
    upstream_url: http://service.controller.infrared
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.controller.plug:
    name: TP-Link Plug Controller
    prefix: service.controller.plug
    upstream_url: http://service.controller.plug
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.dmx:
    name: DMX Service
    prefix: service.dmx
    upstream_url: http://service.dmx
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  device-registry:
    name: Device Registry
    prefix: device-registry
    upstream_url: http://device-registry
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.scene:
    name: Scene Service
    prefix: service.scene
    upstream_url: http://service.scene
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.user:
    name: User Service
    prefix: service.user
    upstream_url: http://service.user
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1
